import '@testing-library/jest-dom';

const noop = () => undefined;
const off = () => undefined;
const ok = { ok: true, data: undefined };

const beeforApi = {
  saveCredentials: async () => ok,
  getCredentials: async () => null,
  clearCredentials: async () => ok,
  getSettings: async () => ({
    autoStart: false,
    autoLoginOnLaunch: true,
    automatePunch: false,
    punchTimes: ['08:00', '12:00', '13:00', '17:00'],
    punchDriftMinutes: 0,
    lunchAlarm: false,
    lunchAlarmTime: '12:00',
    moodNotification: false,
    moodNotificationTime: '09:00',
    moodAlarm: false,
    kudocardNotification: false,
    kudocardFrequency: 'once',
    kudocardDays: [],
    hoursPerDay: 8,
    hourRate: 0,
    patchJournal: '',
  }),
  setSettings: async () => ok,
  getStatus: async () => 'idle',
  login: async () => ok,
  logout: async () => ok,
  verifySession: async () => ({ ok: true, data: 'idle' }),
  autoLancamento: async () => ok,
  selectMood: async () => ok,
  openBeefor: async () => ok,
  lancarHora: async () => ok,
  fetchTimesheet: async () => ({ ok: true, data: [] }),
  getCurrentMood: async () => ({ ok: true, data: null }),
  sendKudoCard: async () => ({ ok: true, data: { message: 'ok' } }),
  searchKudoRecipient: async () => ({ ok: true, data: [] }),
  getKudoCounts: async () => ({ ok: true, data: {} }),
  getKudoLists: async () => ({ ok: true, data: { sent: [], received: [] } }),
  getKudoDetail: async () => ({ ok: true, data: null }),
  fetchTeamMembers: async () => ({ ok: true, data: [] }),
  onStatus: () => off,
  getAdminStatus: async () => ({ elevated: false, platform: 'test' }),
  relaunchAsAdmin: async () => ok,
  relaunchApp: async () => ok,
  testNotification: async () => ok,
  getTodayAlerts: async () => ({ ok: true, data: [] }),
  onPlayAlarm: () => off,
  onNotify: () => off,
  setLunchTimerActive: noop,
  onTrayLunchTimer: () => off,
  onTrayOpenKudo: () => off,
  onTrayOpenCoins: () => off,
  onUpdateAvailable: () => off,
  onUpdateDownloaded: () => off,
  quitAndInstallUpdate: async () => undefined,
  winMinimize: noop,
  winMaximize: noop,
  winClose: noop,
  winSetIcon: noop,
  getAssetPath: async () => '',
  readAsset: async () => null,
  fetchAtividades: async () => ({ ok: true, data: [] }),
  notifyWindows: async () => ok,
  saveCoin2uCreds: async () => ok,
  getCoin2uCreds: async () => null,
  clearCoin2uCreds: async () => ok,
  getCoin2uDashboard: async () => ({ ok: true, data: {} }),
  getCoin2uLog: async () => ({ ok: true, data: {} }),
  getCoin2uShop: async () => ({ ok: true, data: {} }),
  buyCoin2uItem: async () => ({ ok: true, data: true }),
  transferCoin2uCoins: async () => ({ ok: true, data: true }),
  verifyCoin2u: async () => ({ ok: true, data: { userId: 1, email: 'test@example.com' } }),
};

Object.defineProperty(window, 'beefor', {
  value: beeforApi,
  configurable: true,
});
